# Generated by Django 4.2.7 on 2025-04-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_child_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('Infant', 'Infant'), ('Toddler', 'Toddler'), ('Preschool', 'Preschool'), ('School Aged', 'School Aged')], max_length=50)),
                ('activity_name', models.CharField(max_length=100)),
                ('activity_time', models.TimeField()),
                ('activity_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
