# Generated by Django 5.2 on 2025-04-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='activity_date',
            field=models.DateField(),
        ),
    ]
