# Generated by Django 5.2 on 2025-04-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_child_evaluation_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/default-profile.png', upload_to='profile_pics/'),
        ),
    ]
