# Generated by Django 5.2 on 2025-04-28 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_allergy_attendance_childallergy_meal_mealplan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='child_name',
        ),
        migrations.AddField(
            model_name='attendance',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_child', to='accounts.child'),
        ),
    ]
