# Generated by Django 5.2 on 2025-04-28 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_attendance_child_name_attendance_child'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealplan',
            old_name='week_start_date',
            new_name='week_start',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='child',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.group'),
        ),
    ]
