# Generated by Django 4.2.7 on 2025-04-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_schedule_activity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Done', 'Done')], default='Pending', max_length=10),
        ),
    ]
