# Generated by Django 5.2 on 2025-05-09 19:27

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_rename_week_start_date_mealplan_week_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Accident', 'Accident'), ('Illness', 'Illness')], max_length=50)),
                ('medication_administered', models.BooleanField(default=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.child')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('administration_date', models.DateField(default=datetime.datetime.now)),
                ('administered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.child')),
            ],
        ),
    ]
