# Generated by Django 5.1.4 on 2025-05-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_activitysummary_feedback_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='image_path',
            field=models.CharField(blank=True, help_text='Path to milestone image', max_length=255, null=True),
        ),
    ]
