# Generated by Django 5.1.4 on 2025-05-14 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_milestone_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='image_path',
        ),
    ]
